project:
  type: website
  output-dir: docs

website:
  title: "Urban Streams"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Download Met Data"
        file: download-met.qmd
      - text: "Page 2"
        file: page-2.qmd
    right:
      - icon: github
        href: https://github.com/EBGC-group/Urban-Streams

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

